
Description: Spot Fleet for ECS

Parameters:
  VPC:
    Description: The VPC to deploy SpotFleet into
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: The subnets of a VPC to deploy SpotFleet into
    Type: List<AWS::EC2::Subnet::Id>

  ECSCluster:
    Description: The ECS Cluster to register with
    Type: String

  AMI:
    Description: The AMI to launch instances with
    Type: String

  InitialCapacity:
    Description: The initial capacity for the spot fleet
    Type: Number

  MaxPricePerUnitHour:
    Description: The maximum to bid per unit-hour
    Type: String

  KeyName:
    Type: String
    Default: ""

Conditions:
  HasKeyName: !Not [ !Equals [ !Ref KeyName, "" ] ]

Resources:
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Security group for ECS instances"
      GroupDescription: "Security group for ECS instances"
      VpcId: !Ref VPC

  ECSSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ECSSecurityGroup
      SourceSecurityGroupId: !Ref ECSSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535

  SpotFleetIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Statement": [{
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
              "Service": "spotfleet.amazonaws.com"
            }
          }]
        }
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole

  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-ECSRole-${AWS::Region}
      AssumeRolePolicyDocument: |
        {
          "Statement": [{
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            }
          }]
        }
      Policies:
        - PolicyName: ecs-service
          PolicyDocument: |
            {
              "Statement": [{
                "Effect": "Allow",
                "Action": [
                "ecs:CreateCluster",
                "ecs:DeregisterContainerInstance",
                "ecs:DiscoverPollEndpoint",
                "ecs:Poll",
                "ecs:RegisterContainerInstance",
                "ecs:StartTelemetrySession",
                "ecs:Submit*",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken"
                ],
                "Resource": "*"
              }]
            }

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref ECSRole

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            Groups: [ !GetAtt ECSSecurityGroup.GroupId ]
        KeyName: !If [HasKeyName, !Ref KeyName, !Ref "AWS::NoValue"]
        IamInstanceProfile: { Arn: !GetAtt ECSInstanceProfile.Arn }
        ImageId: !Ref AMI
        UserData:
          "Fn::Base64": !Sub |
            Content-Type: multipart/mixed; boundary="==BOUNDARY=="
            MIME-Version: 1.0

            --==BOUNDARY==
            Content-Type: text/x-shellscript; charset="us-ascii"

            #!/bin/bash
            yum install -y aws-cfn-bootstrap
            echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource SpotFleet --region ${AWS::Region}
            --==BOUNDARY==--

  SpotFleet:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: lowestPrice
        IamFleetRole: !GetAtt SpotFleetIAMRole.Arn
        TargetCapacity: !Ref InitialCapacity
        SpotPrice: !Ref MaxPricePerUnitHour
        LaunchSpecifications: 
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 4
              InstanceType: m5.large
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 8
              InstanceType: m5.xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 16
              InstanceType: m5.2xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 32
              InstanceType: m5.4xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 4
              InstanceType: c5.large
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 8
              InstanceType: c5.xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 16
              InstanceType: c5.2xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 32
              InstanceType: c5.4xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 1
              InstanceType: t2.small
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 2
              InstanceType: t2.medium
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 4
              InstanceType: t2.large
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 8
              InstanceType: t2.xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 4
              InstanceType: m4.large
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 8
              InstanceType: m4.xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 16
              InstanceType: m4.2xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 32
              InstanceType: m4.4xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 4
              InstanceType: c4.large
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 8
              InstanceType: c4.xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 16
              InstanceType: c4.2xlarge
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version: !GetAtt "LaunchTemplate.LatestVersionNumber"
            Overrides:
              WeightedCapacity: 32
              InstanceType: c4.4xlarge

Outputs:
  SpotFleet:
    Description: The SpotFleet created
    Value: !Ref SpotFleet
